FROM nginx:1.15.8-alpine

#config
copy ./nginx.conf /etc/nginx/nginx.conf

#content, comment out the ones you dont need!


#copy all in this folder to nginx/html of virtual os

copy . /usr/share/nginx/html/


#if only specific extention is to be copied
# copy ./*.html /usr/share/nginx/html/
#copy ./*.css /usr/share/nginx/html/
#copy ./*.png /usr/share/nginx/html/
#copy ./*.js /usr/share/nginx/html/